### ISSUE TITLE
[Dashboard] Delegating Access

### ISSUE THREAD

**Issue by Mohron** [BadgeUp/badgeup-browser-client#3]
The web dashboard needs to have a way to delegate access to your applications to other users. Most people who will use your server likely have some kind of team they work with and currently you can only have one person access the dashboard without sharing accounts which is horrible practice.

**Comment by MarkHerhold** [comment]
@Mohron You are absolutely correct. We are working on this.

**Comment by Mohron** [comment]
@MarkHerhold Hope you really meant it when your post said you wanted alpha testers!

**Comment by MarkHerhold** [comment]
@Mohron HAHAHA! 😆
Of course I meant it! These are good suggestions and are very helpful, trust me.

Out of curiosity, do you feel that a forum would be beneficial to you to request fixes/enhancements?

**Comment by Mohron** [comment]
@MarkHerhold I personally like what the big plugins for Sponge are doing by running a Discord server for live support and a place to talk out ideas before making a ticket. Much easier to have a conversation with a live messaging system then tickets or a forum IMO.

**Comment by MarkHerhold** [comment]
Hey @Mohron, sorry for not providing an estimate for this. This is honestly one of the more complicated features that needs to be built into the platform. I don't currently have a plan on when this will get implemented because other features/fixes are currently taking precedence.

If this is a one or two-time thing, I will gladly set this up manually but the users will all have 'admin' privileges. Would that suffice for your purposes, or do you need full support for user management? If you would like me to set this up for your users or want to discuss other details, please email me directly at `mark@badgeup.io`. Thanks!

**Comment by Mohron** [comment]
Oh, I can wait. Just trying to find more ways to get you valuable feedback. You guys have been busy lately so I want to help keep it going!

**Comment by Mohron** [comment]
Any timeline on this feature?

**Comment by MarkHerhold** [comment]
We don't have a timeline for this feature being a part of the dashboard. In the meantime, I can point multiple user profiles to the same account for you though. If you want this, please email support@badgeup.io with the users you want to be attached to a specific account.
